# Makefile pro semestralni praci z predmetu BI-PA2, autor: Jakub Votrubec (votruja6)
GXX=g++
CFLAGS=-Wall -Wextra -pedantic -Wextra -std=c++14 -g -lncurses
OUTPUT_FOLDER=bin
OUTPUT_NAME=votruja6
OBJS=$(OUTPUT_FOLDER)/CBeast.o $(OUTPUT_FOLDER)/CCombat.o $(OUTPUT_FOLDER)/CDoor.o \
$(OUTPUT_FOLDER)/CFloor.o $(OUTPUT_FOLDER)/CGame.o $(OUTPUT_FOLDER)/CInventory.o \
$(OUTPUT_FOLDER)/CMovable.o  $(OUTPUT_FOLDER)/CPlayer.o $(OUTPUT_FOLDER)/CPopup.o \
$(OUTPUT_FOLDER)/CWeapon.o $(OUTPUT_FOLDER)/CWear.o $(OUTPUT_FOLDER)/CWearable.o \
$(OUTPUT_FOLDER)/main.o
SOURCE_FOLDER=./src
SOURCES=$(SOURCE_FOLDER)/*.cpp
DOC_FOLDER=./doc
DOXYGEN_CONFIG=./doxygen/dconfig
SAVE_FOLDER=./saves

.PHONY: all
all: compile doc

.PHONY: compile
compile: $(OUTPUT_NAME)

$(OUTPUT_NAME): $(OBJS)
	@mkdir -p $(OUTPUT_FOLDER)
	$(GXX) -o $(OUTPUT_NAME) $^ -lncurses

$(OUTPUT_FOLDER)/%.o: $(SOURCE_FOLDER)/%.cpp
	@mkdir -p $(OUTPUT_FOLDER)
	$(GXX) -c -o $@ $< $(CFLAGS)

.PHONY:run
run: $(OUTPUT_NAME)
	./$^

.PHONY:valgrind
valgrind: $(OUTPUT_NAME)
	valgrind --leak-check=full --show-leak-kinds=all ./$^

.PHONY:doc
doc: $(DOXYGEN_CONFIG)
	doxygen $^

.PHONY: clean
clean: 
	rm -fr $(OUTPUT_FOLDER)
	rm -f $(OUTPUT_NAME)
	rm -fr $(DOC_FOLDER)
	rm -fr $(SAVE_FOLDER)

 # generated by g++ -MM *.cpp
CBeast.o: CBeast.cpp CBeast.hpp CMovable.hpp CTile.hpp TCoordinates.hpp \
 CPopup.hpp EPathfindingType.hpp CFloor.hpp CItem.hpp CStatic.hpp \
 CDoor.hpp CPlayer.hpp CInventory.hpp CWeapon.hpp CWear.hpp CWearable.hpp \
 EArmorType.hpp EBonusType.hpp CCombat.hpp
CCombat.o: CCombat.cpp CCombat.hpp CMovable.hpp CTile.hpp \
 TCoordinates.hpp CPopup.hpp
CDoor.o: CDoor.cpp CDoor.hpp CStatic.hpp CTile.hpp TCoordinates.hpp
CFloor.o: CFloor.cpp CFloor.hpp CTile.hpp TCoordinates.hpp CBeast.hpp \
 CMovable.hpp CPopup.hpp EPathfindingType.hpp CItem.hpp CStatic.hpp \
 CDoor.hpp CPlayer.hpp CInventory.hpp CWeapon.hpp CWear.hpp CWearable.hpp \
 EArmorType.hpp EBonusType.hpp CFood.hpp CConsumable.hpp CPotion.hpp
CGame.o: CGame.cpp CGame.hpp CPlayer.hpp CMovable.hpp CTile.hpp \
 TCoordinates.hpp CPopup.hpp CInventory.hpp CItem.hpp CStatic.hpp \
 CWeapon.hpp CWear.hpp CWearable.hpp EArmorType.hpp EBonusType.hpp \
 CFloor.hpp CBeast.hpp EPathfindingType.hpp CDoor.hpp
CInventory.o: CInventory.cpp CInventory.hpp CItem.hpp CStatic.hpp \
 CTile.hpp TCoordinates.hpp CPlayer.hpp CMovable.hpp CPopup.hpp \
 CWeapon.hpp CWear.hpp CWearable.hpp EArmorType.hpp EBonusType.hpp \
 CFood.hpp CConsumable.hpp CPotion.hpp
CMovable.o: CMovable.cpp CMovable.hpp CTile.hpp TCoordinates.hpp \
 CPopup.hpp CFloor.hpp CBeast.hpp EPathfindingType.hpp CItem.hpp \
 CStatic.hpp CDoor.hpp CPlayer.hpp CInventory.hpp CWeapon.hpp CWear.hpp \
 CWearable.hpp EArmorType.hpp EBonusType.hpp
CPlayer.o: CPlayer.cpp CPlayer.hpp CMovable.hpp CTile.hpp \
 TCoordinates.hpp CPopup.hpp CInventory.hpp CItem.hpp CStatic.hpp \
 CWeapon.hpp CWear.hpp CWearable.hpp EArmorType.hpp EBonusType.hpp \
 CFloor.hpp CBeast.hpp EPathfindingType.hpp CDoor.hpp CCombat.hpp
CPopup.o: CPopup.cpp CPopup.hpp
CWeapon.o: CWeapon.cpp CWeapon.hpp CItem.hpp CStatic.hpp CTile.hpp \
 TCoordinates.hpp CPlayer.hpp CMovable.hpp CPopup.hpp CInventory.hpp \
 CWear.hpp CWearable.hpp EArmorType.hpp EBonusType.hpp
CWearable.o: CWearable.cpp CWearable.hpp CItem.hpp CStatic.hpp CTile.hpp \
 TCoordinates.hpp EArmorType.hpp EBonusType.hpp CPlayer.hpp CMovable.hpp \
 CPopup.hpp CInventory.hpp CWeapon.hpp CWear.hpp
CWear.o: CWear.cpp CWear.hpp CWearable.hpp CItem.hpp CStatic.hpp \
 CTile.hpp TCoordinates.hpp EArmorType.hpp EBonusType.hpp CPlayer.hpp \
 CMovable.hpp CPopup.hpp CInventory.hpp CWeapon.hpp
main.o: main.cpp CGame.hpp CPlayer.hpp CMovable.hpp CTile.hpp \
 TCoordinates.hpp CPopup.hpp CInventory.hpp CItem.hpp CStatic.hpp \
 CWeapon.hpp CWear.hpp CWearable.hpp EArmorType.hpp EBonusType.hpp \
 CFloor.hpp CBeast.hpp EPathfindingType.hpp CDoor.hpp
